# ReplayKitSetup/VersionInfo.cs is the single source of truth for release version; called by build.bat before every build so the checked-in bundled copy never drifts. the live copy at install time is regenerated by Installer.WriteReplaykitVersion regardless -- this only keeps the repo-tracked asset self-consistent.
$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$versionInfoPath = Join-Path $repoRoot "ReplayKitSetup\VersionInfo.cs"
$outPath = Join-Path $repoRoot "assets\obs-studio\obs-replayKit\version.json"

if (-not (Test-Path -LiteralPath $versionInfoPath)) {
    throw "Missing version source: $versionInfoPath"
}
$match = Select-String -LiteralPath $versionInfoPath -Pattern 'Version\s*=\s*"([^"]+)"' | Select-Object -First 1
if (-not $match) {
    throw "Could not find Version in $versionInfoPath"
}
$version = $match.Matches[0].Groups[1].Value

New-Item -ItemType Directory -Force -Path (Split-Path -Parent $outPath) | Out-Null
$json = "{`r`n  ""version"": ""$version""`r`n}`r`n"
[System.IO.File]::WriteAllText($outPath, $json, [System.Text.UTF8Encoding]::new($false))

Write-Host "    ReplayKit version $version"
